apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - path: helm/api-golang
            namespace: demo-app
            name: api-golang
          - path: helm/api-node
            namespace: demo-app
            name: api-node
          - path: helm/client-react
            namespace: demo-app
            name: client-react
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/vmmaltsev/gitops-helm.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          skipCrds: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
