apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/vmmaltsev/gitops-helm.git
        revision: HEAD
        directories:
          - path: helm/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/vmmaltsev/gitops-helm.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          skipCrds: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ if eq path.basename "monitoring" }}monitoring{{ else }}demo-app{{ end }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
