apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - path
        generators:
          - git:
              repoURL: https://github.com/vmmaltsev/gitops-helm.git
              revision: HEAD
              directories:
                - path: helm/*
          - list:
              elements:
                - path: helm/monitoring
                  namespace: monitoring
                - path: helm/api-golang
                  namespace: demo-app
                - path: helm/api-node
                  namespace: demo-app
                - path: helm/client-react
                  namespace: demo-app
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/vmmaltsev/gitops-helm.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          skipCrds: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
