apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/vmmaltsev/gitops-helm.git
        revision: HEAD
        directories:
          - path: helm/monitoring
  template:
    metadata:
      name: monitoring
    spec:
      project: default
      source:
        repoURL: https://github.com/vmmaltsev/gitops-helm.git
        targetRevision: HEAD
        path: helm/monitoring
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
