image:
  repository: maltsevvm/demo-app-api-golang
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8000

env:
  databaseUrl:
    secretName: db-secret
    secretKey: DATABASE_URL
