apiVersion: v1
kind: Service
metadata:
  name: api-node
spec:
  selector:
    app: api-node
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
