kube-prometheus-stack:
  prometheusOperator:
    cleanupCustomResource: false
    createCustomResource: false

  prometheus:
    enabled: true
    ingress:
      enabled: false  # В GKE обычно не открывают Prometheus наружу
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false

  alertmanager:
    enabled: true
    ingress:
      enabled: false

  grafana:
    enabled: true
    defaultDashboardsEnabled: true
    admin:
      existingSecret: grafana-admin-secret  # Используем секрет вместо открытого пароля
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "20m"
      path: /
      pathType: Prefix
      hosts:
        - grafana.maltsevtech.com
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.maltsevtech.com
    service:
      type: ClusterIP

  kubeApiServer:
    enabled: true

  nodeExporter:
    enabled: true

  kubeStateMetrics:
    enabled: true
