image:
  repository: maltsevvm/demo-app-client-react
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: app.maltsevtech.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
