apiVersion: v1
kind: ConfigMap
metadata:
  name: api-golang-config
  labels:
    app: api-golang
data:
  APP_ENV: {{ .Values.env.appEnv | default "production" }}
  LOG_LEVEL: {{ .Values.env.logLevel | default "info" }} 