apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-golang
  labels:
    app: api-golang
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-golang
  template:
    metadata:
      labels:
        app: api-golang
    spec:
      containers:
        - name: api-golang
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.databaseUrl.secretName }}
                  key: {{ .Values.env.databaseUrl.secretKey }}
