{{- if gt .Values.replicaCount 1.0 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-golang-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-golang
{{- end }} 