apiVersion: v1
kind: Service
metadata:
  name: api-golang
spec:
  selector:
    app: api-golang
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
