image:
  repository: maltsevvm/demo-app-api-node
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

env:
  databaseUrl:
    secretName: db-secret
    secretKey: DATABASE_URL
