image:
  repository: maltsevvm/demo-app-api-node
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

env:
  nodeEnv: production
  logLevel: info
  databaseUrl:
    secretName: db-secret
    secretKey: DATABASE_URL
